print("RRRRRRRRRRR            OOOOOOOOOOO")
print("R           R         O           O ")
print("R            R       O             O")
print("R           R        O             O")
print("RRRRRRRRRRR          O             O")
print("R       R            O             O")
print("R        R           O             O")
print("R         R          O             O")
print("R          R          O           O")
print("R           R          OOOOOOOOOOO")