print(" XXXXXXXXXXXXXXXXXX ")
print("X                  X")
print("X    _       _     X")
print("X    0       0     X")
print("X  __    ^     __  X")
print("X   \          /   X")
print("X    \________/    X")
print("X                  X")
print(" XXXXXXXXXXXXXXXXXX ")